### PR TITLE
These are necessary to make the entire blaze-* family happy with GHC 7.7

### PR DESCRIPTION
**Pull request by ggreif**
Yo may need to add CPP conditionals depending on which is the oldest GHC you need to support. I'll gladly amend this pull request if you want.

Cheers,

```
Gabor
```

### CODE REVIEW

**Comment by meiersi** [comment]
Hi @ggreif, thank you for the patch. My goal is to support GHC 7.x, if possible. I'm right now installing them on my machine to check for myself :-)

**Comment by meiersi** [comment]
Hi @ggreif, I've incorporated your changes with a bunch of other fixes to remove warnings and keep compilation for GHC 7.0.x and GHC 7.4.x. See 0dde6e187c420623b368ea35fc38962ce2b71609.

Could you check on your system that this compiles with GHC HEAD? I don't have it installed yet.

**Comment by meiersi** [comment]
This is actually an easier view to see the changes I meant: https://github.com/meiersi/blaze-builder/commits/master

**Comment by ggreif** [comment]
Yes this builds :-)

I get one warning, though:

[ 7 of 13] Compiling Blaze.ByteString.Builder.ByteString (
Blaze/ByteString/Builder/ByteString.hs,
dist/build/Blaze/ByteString/Builder/ByteString.o )

Blaze/ByteString/Builder/ByteString.hs:61:1: Warning:
    The qualified import of `Data.ByteString.Lazy.Internal' is redundant
      except perhaps to import instances from`Data.ByteString.Lazy.Internal'
    To import instances alone, use: import Data.ByteString.Lazy.Internal()

Maybe removing the import works for you?

Cheers,

```
Gabor
```

$ git diff
diff --git a/Blaze/ByteString/Builder/ByteString.hs
b/Blaze/ByteString/Builder/ByteString.hs
index 9cb529f..0e95945 100644
--- a/Blaze/ByteString/Builder/ByteString.hs
+++ b/Blaze/ByteString/Builder/ByteString.hs
@@ -58,7 +58,6 @@ import qualified Data.ByteString.Base as S
 import qualified Data.ByteString.Lazy.Base as L -- FIXME: check if
this is the right module
 #else
 import qualified Data.ByteString.Internal      as S
-import qualified Data.ByteString.Lazy.Internal as L
 #endif

**Comment by meiersi** [comment]
Thanks for testing. The warning is due to the move of foldrChunks from Internal to public in bytestring 0.9 -> 0.10

I'll add an ignore pragma.

**Comment by meiersi** [comment]
Fixed the last warning and released to hackage: http://hackage.haskell.org/package/blaze-builder-0.3.1.1

**Pull request closed without merging**
